  ;; ═══ own.wat — ownership inline helpers (Tier 7) ════════════════════
  ;; Implements: Hβ-infer-substrate.md §5 (ownership inference inline) +
  ;;             §6.2 + §7.3 + §8.1 own.wat row + §8.4 line estimate
  ;;             (revised this commit ~280-340 lines per the OwnershipViolation
  ;;             diagnostic helper landing here per emit_diag.wat:189-195's
  ;;             stated delegation; ROADMAP §4 closure pattern) +
  ;;             §11.2 + §11.5 + §13.3 dep order #7 +
  ;;             docs/specs/04-inference.md §Ownership inference +
  ;;             docs/specs/07-ownership.md (canonical Consume effect
  ;;             surface + affine_ledger handler + ref escape check) +
  ;;             src/own.mn (canonical contract — affine_ledger arms
  ;;             at lines 86-155, check_ref_escape at 371-376,
  ;;             find_first_span at 351-360, set_diff/set_union/
  ;;             set_intersect via runtime/strings.mn).
  ;;
  ;; Realizes the affine_ledger projection of primitive #5 (Ownership as
  ;; effect — DESIGN.md §0.5) at the seed substrate. Each walk-arm site
  ;; that detects double-consume / ref-escape / branch-collision routes
  ;; through this chunk's helpers; diagnostics surface via $eprint_string +
  ;; $graph_bind_kind with Reason::Inferred("ownership: <subtype>") per
  ;; the Hazel productive-under-error pattern (spec 04 §Error handling).
  ;;
  ;; Exports:    $infer_consume_use,
  ;;             $infer_consume_seen,
  ;;             $infer_branch_enter,
  ;;             $infer_branch_divider,
  ;;             $infer_branch_exit,
  ;;             $infer_ref_escape_check_at_return,
  ;;             $infer_ref_escape_clear,
  ;;             $infer_used_clear,
  ;;             $infer_emit_ownership_violation,
  ;;             $infer_emit_ref_escape,
  ;;             $infer_emit_branch_collision
  ;; Uses:       $alloc (alloc.wat),
  ;;             $str_eq / $str_concat / $str_alloc (str.wat),
  ;;             $eprint_string (wasi.wat — fd 2 stderr),
  ;;             $int_to_str (int.wat),
  ;;             $make_list / $list_index / $list_set /
  ;;               $list_extend_to / $len / $slice (list.wat),
  ;;             $make_record / $record_get / $record_set /
  ;;               $tag_of (record.wat),
  ;;             $graph_bind_kind / $node_kind_make_nerrorhole (graph.wat),
  ;;             $infer_init / $infer_ref_escape_push /
  ;;               $infer_ref_escape_len /
  ;;               $infer_ref_escape_clear_state (state.wat — last
  ;;               added per E2 of own.wat plan),
  ;;             $reason_make_inferred / $reason_make_located (reason.wat).
  ;; Test:       bootstrap/test/infer/own_consume_first.wat,
  ;;             bootstrap/test/infer/own_consume_double.wat,
  ;;             bootstrap/test/infer/own_branch_collision.wat,
  ;;             bootstrap/test/infer/own_ref_escape.wat
  ;;
  ;; ═══ EIGHT INTERROGATIONS (per Hβ-infer-substrate.md §6 applied to
  ;;                            own.wat ownership inline) ═══════════════
  ;;
  ;; 1. Graph?      WRITES via $graph_bind_kind on violation
  ;;                (NErrorHole(Reason::Inferred(...))); NO new reads.
  ;;                Productive-under-error: handle bound to NErrorHole +
  ;;                walk continues per spec 04 Hazel pattern.
  ;; 2. Handler?    Direct seed call; the wheel's affine_ledger handler
  ;;                routes its OneShot-resume arms through these helpers
  ;;                (consume / branch_enter / branch_divider / branch_exit
  ;;                map 1-1 to src/own.mn:86-155).
  ;; 3. Verb?       N/A at primitive level (ownership inline; each helper
  ;;                is a direct call from a walk-arm site).
  ;; 4. Row?        Consume signal generated by walk_expr.wat's VarRef-of-
  ;;                own arm; this chunk is violator-detector, not row-
  ;;                composer (composition lives in row.wat).
  ;; 5. Ownership?  Message strings own (constructed by $str_concat;
  ;;                bump-allocator monotonic); name/span/handle ref;
  ;;                ledger entries (used / used_sites / branches frames)
  ;;                own by FnStmt-scoped lifecycle ($infer_used_clear at
  ;;                FnStmt exit + $infer_ref_escape_clear; trail-bound
  ;;                graph mutations preserved via $graph_bind_kind).
  ;; 6. Refinement? N/A (refinement-aware ownership is named follow-up
  ;;                Hβ.infer.refinement-compose per §12).
  ;; 7. Gradient?   Each diagnostic IS one gradient signal; Mentl voice
  ;;                composes post-L1 on this surface (canonical fix
  ;;                proposals: change `ref` to `own`; refactor body so
  ;;                name escapes as owned; add explicit consume).
  ;; 8. Reason?     Located(span, Inferred("ownership: <subtype>")) for
  ;;                cause chain on the offending bind; NErrorHole wraps
  ;;                Inferred("ownership double-consume" /
  ;;                "ownership ref escape" / "ownership branch collision")
  ;;                so downstream Why Engine walks see both the located
  ;;                cause AND the diagnostic-class.
  ;;
  ;; ═══ FORBIDDEN PATTERNS AUDIT (per Hβ-infer-substrate.md §7 +
  ;;                                applied to own.wat) ═══════════════
  ;;
  ;; - Drift 1 (Rust vtable):           3 emit helpers ($infer_emit_
  ;;                                    ownership_violation / _ref_escape /
  ;;                                    _branch_collision) are peer
  ;;                                    functions, NOT a table indexed by
  ;;                                    violation-code.
  ;; - Drift 2 (Scheme env frame):      Ledger lives in module-level
  ;;                                    globals (mirrors state.wat
  ;;                                    precedent), NOT a parameter chain
  ;;                                    threaded through every helper.
  ;; - Drift 3 (Python dict):           Reason-class identifiers are
  ;;                                    data-segment string constants
  ;;                                    emitted via $eprint_string +
  ;;                                    passed to $reason_make_inferred,
  ;;                                    NOT $str_eq enum dispatch.
  ;; - Drift 4 (Haskell monad transformer): Direct functions; no
  ;;                                    OwnershipM / LedgerM monad.
  ;; - Drift 5 (C calling convention):  Direct i32 params (handle, name,
  ;;                                    span, reason); no bundled context
  ;;                                    struct + state ptr.
  ;; - Drift 6 (primitive special-case): Consume is a regular row entry
  ;;                                    composed via row.wat; NOT a
  ;;                                    compiler intrinsic. NErrorHole
  ;;                                    discipline matches every other
  ;;                                    Reason class.
  ;; - Drift 7 (parallel-arrays):       used_sites entries are
  ;;                                    $make_record(USED_SITE_ENTRY=213,
  ;;                                    arity=2); branches frames are
  ;;                                    $make_record(BRANCH_FRAME=214,
  ;;                                    arity=2). NEVER parallel
  ;;                                    `(name_ptrs[], span_ptrs[])` arrays.
  ;; - Drift 8 (mode flag / string-keyed): Each violation class has its
  ;;                                    peer helper function — NOT
  ;;                                    $infer_emit_violation(handle,
  ;;                                    kind:Int, ...) with int-coded
  ;;                                    dispatch.
  ;; - Drift 9 (deferred-by-omission):  Every src/own.mn affine_ledger
  ;;                                    arm has a substrate projection
  ;;                                    HERE (consume / branch_enter /
  ;;                                    branch_divider / branch_exit +
  ;;                                    check_ref_escape) OR is named as
  ;;                                    a peer follow-up (region_tracker
  ;;                                    = Hβ.infer.region-tracker;
  ;;                                    used-set deque + binary-search =
  ;;                                    Hβ.infer.used-binary-search /
  ;;                                    .used-sites-deque per §12).
  ;;
  ;; - Foreign fluency — Rust borrow checker: Vocabulary IS "Consume
  ;;                                    effect", "affine ledger", "ref-
  ;;                                    escape tracker", "FnStmt-exit
  ;;                                    check". NEVER "borrow",
  ;;                                    "lifetime", "region ID" (region
  ;;                                    surfaces as named follow-up
  ;;                                    Hβ.infer.region-tracker; until
  ;;                                    then no region vocabulary in
  ;;                                    helper names or comments).
  ;;
  ;; - Foreign fluency — exception machinery: NO "throw" / "panic" /
  ;;                                    "raise" / "exception" / "catch"
  ;;                                    vocabulary. NErrorHole IS the
  ;;                                    productive-under-error substrate.
  ;;
  ;; ═══ TAG REGION ═══════════════════════════════════════════════════
  ;;
  ;; Per Hβ-infer-substrate.md §2.1 reserved region 200-219 for non-
  ;; Reason infer-private records. state.wat consumed 210/211/212;
  ;; own.wat extends with:
  ;;
  ;;   USED_SITE_ENTRY = 213  ;; (name_str, span) — insertion-ordered
  ;;                          ;; first-use diagnosis log
  ;;   BRANCH_FRAME    = 214  ;; (base_used_list, deltas_list) — branch
  ;;                          ;; protocol stack frame per src/own.mn:118-154
  ;;
  ;; Tag 215 reserved for Hβ.infer.region-tracker follow-up (Tofte-Talpin
  ;; region tag record; lands when Hβ.lower's Alloc surface matures).
  ;;
  ;; Tag 200, 201, 202, 215-219 still free for future infer-private
  ;; records (per Hβ-infer §2.1 region accounting; 17 - 5 used = 12 free
  ;; for non-Reason infer-private records).

  ;; ─── Module-level globals (ledger substrate) ──────────────────────
  ;;
  ;; The seed projects affine_ledger's handler-state (used / used_sites /
  ;; branches per src/own.mn:86) onto module-level globals in this chunk.
  ;; The wheel's compiled form will route handler-state through the
  ;; closure-style state.wat additions per H7 multi-shot continuation
  ;; substrate; the seed's globals are the per-walk projection, cleared
  ;; at $infer_used_clear (FnStmt exit) per src/own.mn scope discipline.

  (global $own_initialized       (mut i32) (i32.const 0))

  ;; used — flat list of i32 string ptrs, append-at-end set semantics
  ;; ($infer_consume_seen rejects duplicates so the list is effectively
  ;; deduplicated by construction). Sort-preservation as binary-search
  ;; substrate is named follow-up Hβ.infer.used-binary-search per §12.
  (global $infer_used_ptr        (mut i32) (i32.const 0))
  (global $infer_used_len_g      (mut i32) (i32.const 0))

  ;; used_sites — flat list of (name_str, span) records tagged
  ;; USED_SITE_ENTRY=213. Insertion-ordered (most-recent at index 0)
  ;; via shift-right-insert per src/own.mn:112 `[(name, span)] ++ used_sites`
  ;; convention. find_first_span walks tail-to-head returning the last
  ;; matching entry's span (the actual first-use temporal occurrence).
  ;; Deque substrate as O(1)-per-push upgrade is named follow-up
  ;; Hβ.infer.used-sites-deque per §12.
  (global $infer_used_sites_ptr  (mut i32) (i32.const 0))
  (global $infer_used_sites_len_g (mut i32) (i32.const 0))

  ;; branches — stack of branch frames tagged BRANCH_FRAME=214; each
  ;; frame is (base_used_snapshot, deltas_list). Top of stack at index 0
  ;; (push via shift-right-insert; pop via shift-left-removal). Stack
  ;; shape supports nested branching per src/own.mn:117-154.
  (global $infer_branches_ptr    (mut i32) (i32.const 0))
  (global $infer_branches_len_g  (mut i32) (i32.const 0))

  ;; ─── Idempotent initializer ──────────────────────────────────────
  ;; Allocates initial buffers for ledger globals. Initial capacity 8
  ;; per buffer; $list_extend_to grows on demand. Public-entry helpers
  ;; ($infer_consume_use / _seen / _branch_*) call this so the seed
  ;; can drive ownership inference from any entry point.
  (func $own_init
    (if (i32.eqz (global.get $own_initialized))
      (then
        (global.set $infer_used_ptr        (call $make_list (i32.const 8)))
        (global.set $infer_used_len_g      (i32.const 0))
        (global.set $infer_used_sites_ptr  (call $make_list (i32.const 8)))
        (global.set $infer_used_sites_len_g (i32.const 0))
        (global.set $infer_branches_ptr    (call $make_list (i32.const 8)))
        (global.set $infer_branches_len_g  (i32.const 0))
        (global.set $own_initialized       (i32.const 1)))))

  ;; ─── Data segment — diagnostic message fragments ──────────────────
  ;;
  ;; Offsets ≥ 3136 to sit above unify.wat's 3008-3128 segment region
  ;; (verified via grep audit at chunk-author time per the plan's
  ;; Critical Attention Surface #2 + length-prefix discipline #1).
  ;; Below HEAP_BASE = 4096 per CLAUDE.md memory model; below the
  ;; bump allocator's $heap_ptr init at 1 MiB. 32-byte slot stride per
  ;; the emit_diag.wat / unify.wat precedent.

  (data (i32.const 3136) "\16\00\00\00E_OwnershipViolation: ")              ;; 22 bytes payload
  (data (i32.const 3168) "\1a\00\00\00 consumed twice (first at ")          ;; 26 bytes payload
  (data (i32.const 3200) "\02\00\00\00')")                                  ;; 2 bytes payload
  (data (i32.const 3208) "\01\00\00\00'")                                   ;; 1 byte payload
  (data (i32.const 3216) "\1d\00\00\00 escapes its scope (returned)")       ;; 29 bytes payload
  (data (i32.const 3256) "\22\00\00\00 consumed in two parallel branches")  ;; 34 bytes payload
  (data (i32.const 3296) "\18\00\00\00ownership double-consume")            ;; 24 bytes payload
  (data (i32.const 3328) "\14\00\00\00ownership ref escape")                ;; 20 bytes payload
  (data (i32.const 3352) "\1a\00\00\00ownership branch collision")          ;; 26 bytes payload

  ;; ═══ PRIVATE HELPERS — used / used_sites / branches manipulation ═══

  ;; $own_used_insert(name) — append name to used list (set semantics
  ;; preserved by the consume_seen pre-check rejecting duplicates).
  ;; Append-at-end per planner decision; sort-preservation deferred to
  ;; Hβ.infer.used-binary-search.
  (func $own_used_insert (param $name i32)
    (local $new_len i32)
    (call $own_init)
    (local.set $new_len (i32.add (global.get $infer_used_len_g) (i32.const 1)))
    (global.set $infer_used_ptr
      (call $list_extend_to (global.get $infer_used_ptr) (local.get $new_len)))
    (drop (call $list_set (global.get $infer_used_ptr)
                          (global.get $infer_used_len_g)
                          (local.get $name)))
    (global.set $infer_used_len_g (local.get $new_len)))

  ;; $own_list_contains_str(list, name) — linear scan with $str_eq.
  ;; Returns 1 if name found, 0 otherwise. Used by $infer_consume_seen,
  ;; set_diff, set_intersect, ref-escape check.
  (func $own_list_contains_str (param $list i32) (param $name i32) (result i32)
    (local $n i32) (local $i i32)
    (local.set $n (call $len (local.get $list)))
    (local.set $i (i32.const 0))
    (block $found
      (block $done
        (loop $iter
          (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
          (br_if $found (call $str_eq
                          (call $list_index (local.get $list) (local.get $i))
                          (local.get $name)))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $iter)))
      (return (i32.const 0)))
    (i32.const 1))

  ;; $own_used_sites_push(name, span) — shift-right insert at index 0
  ;; ($make_record(USED_SITE_ENTRY=213, arity=2)). Most-recent entry at
  ;; head per src/own.mn:112. O(N) per push — deque upgrade is named
  ;; follow-up Hβ.infer.used-sites-deque per §12.
  (func $own_used_sites_push (param $name i32) (param $span i32)
    (local $entry i32) (local $new_len i32) (local $i i32)
    (call $own_init)
    (local.set $entry (call $make_record (i32.const 213) (i32.const 2)))
    (call $record_set (local.get $entry) (i32.const 0) (local.get $name))
    (call $record_set (local.get $entry) (i32.const 1) (local.get $span))
    (local.set $new_len (i32.add (global.get $infer_used_sites_len_g) (i32.const 1)))
    (global.set $infer_used_sites_ptr
      (call $list_extend_to (global.get $infer_used_sites_ptr) (local.get $new_len)))
    ;; Shift-right: copy index k → k+1 for k = old_len-1 down to 0.
    (local.set $i (global.get $infer_used_sites_len_g))
    (block $shift_done
      (loop $shift
        (br_if $shift_done (i32.eqz (local.get $i)))
        (drop (call $list_set (global.get $infer_used_sites_ptr)
                              (local.get $i)
                              (call $list_index
                                (global.get $infer_used_sites_ptr)
                                (i32.sub (local.get $i) (i32.const 1)))))
        (local.set $i (i32.sub (local.get $i) (i32.const 1)))
        (br $shift)))
    (drop (call $list_set (global.get $infer_used_sites_ptr)
                          (i32.const 0)
                          (local.get $entry)))
    (global.set $infer_used_sites_len_g (local.get $new_len)))

  ;; $own_find_first_span(name) — returns the SPAN of the LAST matching
  ;; used_sites entry, which is the temporal first-use (entries are
  ;; head-most-recent per shift-right-insert; the tail entry was
  ;; inserted earliest). Per src/own.mn:351-360. Returns 0 (no span
  ;; recorded) on miss.
  (func $own_find_first_span (param $name i32) (result i32)
    (local $n i32) (local $i i32) (local $entry i32) (local $found i32)
    (call $own_init)
    (local.set $n (global.get $infer_used_sites_len_g))
    (local.set $i (i32.const 0))
    (local.set $found (i32.const 0))
    (block $done
      (loop $iter
        (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $entry (call $list_index (global.get $infer_used_sites_ptr)
                                            (local.get $i)))
        (if (call $str_eq
              (call $record_get (local.get $entry) (i32.const 0))
              (local.get $name))
          (then (local.set $found (call $record_get (local.get $entry) (i32.const 1)))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $iter)))
    (local.get $found))

  ;; $own_used_replace(new_list) — replace used buffer + sync length
  ;; from the new_list's $len. Per src/own.mn:111 `with used = ...`
  ;; convention.
  (func $own_used_replace (param $new_list i32)
    (call $own_init)
    (global.set $infer_used_ptr (local.get $new_list))
    (global.set $infer_used_len_g (call $len (local.get $new_list))))

  ;; $own_set_diff(a, b) — flat-list set difference a \ b. Buffer-counter
  ;; substrate per CLAUDE.md bug-class avoidance ($list_extend_to +
  ;; $list_set + counter + $slice). Returns a tag-4 slice view.
  (func $own_set_diff (param $a i32) (param $b i32) (result i32)
    (local $n i32) (local $i i32) (local $count i32) (local $buf i32)
    (local $name i32)
    (local.set $n (call $len (local.get $a)))
    (local.set $buf (call $make_list (local.get $n)))
    (local.set $i (i32.const 0))
    (local.set $count (i32.const 0))
    (block $done
      (loop $iter
        (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $name (call $list_index (local.get $a) (local.get $i)))
        (if (i32.eqz (call $own_list_contains_str (local.get $b) (local.get $name)))
          (then
            (local.set $buf (call $list_extend_to (local.get $buf)
                                                  (i32.add (local.get $count)
                                                           (i32.const 1))))
            (drop (call $list_set (local.get $buf) (local.get $count)
                                  (local.get $name)))
            (local.set $count (i32.add (local.get $count) (i32.const 1)))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $iter)))
    (call $slice (local.get $buf) (i32.const 0) (local.get $count)))

  ;; $own_set_intersect(a, b) — flat-list set intersection. Buffer-counter
  ;; substrate. Returns a tag-4 slice view.
  (func $own_set_intersect (param $a i32) (param $b i32) (result i32)
    (local $n i32) (local $i i32) (local $count i32) (local $buf i32)
    (local $name i32)
    (local.set $n (call $len (local.get $a)))
    (local.set $buf (call $make_list (local.get $n)))
    (local.set $i (i32.const 0))
    (local.set $count (i32.const 0))
    (block $done
      (loop $iter
        (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $name (call $list_index (local.get $a) (local.get $i)))
        (if (call $own_list_contains_str (local.get $b) (local.get $name))
          (then
            (local.set $buf (call $list_extend_to (local.get $buf)
                                                  (i32.add (local.get $count)
                                                           (i32.const 1))))
            (drop (call $list_set (local.get $buf) (local.get $count)
                                  (local.get $name)))
            (local.set $count (i32.add (local.get $count) (i32.const 1)))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $iter)))
    (call $slice (local.get $buf) (i32.const 0) (local.get $count)))

  ;; $own_set_union(a, b) — copy a verbatim; append b entries not in a.
  ;; Buffer-counter substrate.
  (func $own_set_union (param $a i32) (param $b i32) (result i32)
    (local $na i32) (local $nb i32) (local $i i32) (local $count i32)
    (local $buf i32) (local $name i32)
    (local.set $na (call $len (local.get $a)))
    (local.set $nb (call $len (local.get $b)))
    (local.set $buf (call $make_list (i32.add (local.get $na) (local.get $nb))))
    ;; Copy a verbatim
    (local.set $i (i32.const 0))
    (block $done_a
      (loop $copy_a
        (br_if $done_a (i32.ge_u (local.get $i) (local.get $na)))
        (drop (call $list_set (local.get $buf) (local.get $i)
                              (call $list_index (local.get $a) (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $copy_a)))
    (local.set $count (local.get $na))
    ;; Append b entries not in a
    (local.set $i (i32.const 0))
    (block $done_b
      (loop $copy_b
        (br_if $done_b (i32.ge_u (local.get $i) (local.get $nb)))
        (local.set $name (call $list_index (local.get $b) (local.get $i)))
        (if (i32.eqz (call $own_list_contains_str (local.get $a) (local.get $name)))
          (then
            (drop (call $list_set (local.get $buf) (local.get $count)
                                  (local.get $name)))
            (local.set $count (i32.add (local.get $count) (i32.const 1)))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $copy_b)))
    (call $slice (local.get $buf) (i32.const 0) (local.get $count)))

  ;; $own_set_union_all(base, deltas) — fold $own_set_union over deltas
  ;; starting from base. Per src/own.mn:160-170 union_all_deltas.
  (func $own_set_union_all (param $base i32) (param $deltas i32) (result i32)
    (local $n i32) (local $i i32) (local $acc i32)
    (local.set $n (call $len (local.get $deltas)))
    (local.set $acc (local.get $base))
    (local.set $i (i32.const 0))
    (block $done
      (loop $iter
        (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $acc (call $own_set_union
                          (local.get $acc)
                          (call $list_index (local.get $deltas) (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $iter)))
    (local.get $acc))

  ;; $own_list_cons(head, tail) — prepend head to tail returning a fresh
  ;; flat list. Per src/own.mn:135 `[delta] ++ deltas` convention.
  (func $own_list_cons (param $head i32) (param $tail i32) (result i32)
    (local $n i32) (local $i i32) (local $out i32)
    (local.set $n (call $len (local.get $tail)))
    (local.set $out (call $make_list (i32.add (local.get $n) (i32.const 1))))
    (drop (call $list_set (local.get $out) (i32.const 0) (local.get $head)))
    (local.set $i (i32.const 0))
    (block $done
      (loop $iter
        (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
        (drop (call $list_set (local.get $out)
                              (i32.add (local.get $i) (i32.const 1))
                              (call $list_index (local.get $tail) (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $iter)))
    (local.get $out))

  ;; $own_branches_pop_head — shift-left removal of branches[0]. Used by
  ;; $infer_branch_exit per src/own.mn:153 list_tail(branches).
  (func $own_branches_pop_head
    (local $n i32) (local $i i32)
    (call $own_init)
    (local.set $n (global.get $infer_branches_len_g))
    (if (i32.eqz (local.get $n)) (then (return)))
    (local.set $i (i32.const 0))
    (block $done
      (loop $iter
        (br_if $done (i32.ge_u (i32.add (local.get $i) (i32.const 1)) (local.get $n)))
        (drop (call $list_set (global.get $infer_branches_ptr)
                              (local.get $i)
                              (call $list_index
                                (global.get $infer_branches_ptr)
                                (i32.add (local.get $i) (i32.const 1)))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $iter)))
    (global.set $infer_branches_len_g
      (i32.sub (local.get $n) (i32.const 1))))

  ;; $own_used_snapshot — deep-copy the current used list into a fresh
  ;; flat list (used as branch frame's base snapshot per
  ;; src/own.mn:118-121 `branches = [(used, [])] ++ branches`).
  (func $own_used_snapshot (result i32)
    (local $n i32) (local $i i32) (local $out i32)
    (call $own_init)
    (local.set $n (global.get $infer_used_len_g))
    (local.set $out (call $make_list (local.get $n)))
    (local.set $i (i32.const 0))
    (block $done
      (loop $iter
        (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
        (drop (call $list_set (local.get $out) (local.get $i)
                              (call $list_index (global.get $infer_used_ptr)
                                                (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $iter)))
    (local.get $out))

  ;; $own_check_branch_collisions(deltas, span, reason) — pairwise (i,j)
  ;; with i<j; intersect deltas[i] × deltas[j]; emit per-name collision
  ;; via $infer_emit_branch_collision. Per src/own.mn:179-197 +
  ;; report_branch_collisions / report_collisions_inner /
  ;; report_each_collision.
  (func $own_check_branch_collisions (param $deltas i32) (param $span i32)
                                       (param $reason i32)
    (local $n i32) (local $i i32) (local $j i32) (local $k i32) (local $kn i32)
    (local $delta_i i32) (local $delta_j i32) (local $collisions i32)
    (local.set $n (call $len (local.get $deltas)))
    (local.set $i (i32.const 0))
    (block $done_i
      (loop $iter_i
        (br_if $done_i (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $delta_i (call $list_index (local.get $deltas) (local.get $i)))
        (local.set $j (i32.add (local.get $i) (i32.const 1)))
        (block $done_j
          (loop $iter_j
            (br_if $done_j (i32.ge_u (local.get $j) (local.get $n)))
            (local.set $delta_j (call $list_index (local.get $deltas)
                                                  (local.get $j)))
            (local.set $collisions (call $own_set_intersect
                                          (local.get $delta_i)
                                          (local.get $delta_j)))
            (local.set $kn (call $len (local.get $collisions)))
            (local.set $k (i32.const 0))
            (block $done_k
              (loop $iter_k
                (br_if $done_k (i32.ge_u (local.get $k) (local.get $kn)))
                (call $infer_emit_branch_collision
                  (call $list_index (local.get $collisions) (local.get $k))
                  (local.get $span)
                  (local.get $reason))
                (local.set $k (i32.add (local.get $k) (i32.const 1)))
                (br $iter_k)))
            (local.set $j (i32.add (local.get $j) (i32.const 1)))
            (br $iter_j)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $iter_i))))

  ;; ═══ PUBLIC API ═══════════════════════════════════════════════════

  ;; $infer_consume_seen(name) — returns 1 if name has been consumed
  ;; in the current FnStmt body. Linear scan; binary-search upgrade is
  ;; Hβ.infer.used-binary-search per §12.
  (func $infer_consume_seen (param $name i32) (result i32)
    (call $own_init)
    (call $own_list_contains_str (global.get $infer_used_ptr) (local.get $name)))

  ;; $infer_consume_use(handle, name, span, reason) — main entry point
  ;; for the Consume effect's affine_ledger arm per src/own.mn:88-114.
  ;; If name already consumed: emit double-consume diagnostic. Else:
  ;; insert into used + push (name, span) to used_sites.
  (func $infer_consume_use (param $handle i32) (param $name i32)
                            (param $span i32) (param $reason i32)
    (local $first_span i32)
    (call $own_init)
    (if (call $infer_consume_seen (local.get $name))
      (then
        (local.set $first_span (call $own_find_first_span (local.get $name)))
        (call $infer_emit_ownership_violation
          (local.get $handle) (local.get $name) (local.get $span)
          (local.get $first_span) (local.get $reason)))
      (else
        (call $own_used_insert (local.get $name))
        (call $own_used_sites_push (local.get $name) (local.get $span)))))

  ;; $infer_branch_enter — push fresh frame (snapshot, empty deltas) to
  ;; branches stack. Per src/own.mn:118-121.
  (func $infer_branch_enter
    (local $snapshot i32) (local $deltas i32) (local $frame i32)
    (local $new_len i32) (local $i i32)
    (call $own_init)
    (local.set $snapshot (call $own_used_snapshot))
    (local.set $deltas (call $make_list (i32.const 0)))
    (local.set $frame (call $make_record (i32.const 214) (i32.const 2)))
    (call $record_set (local.get $frame) (i32.const 0) (local.get $snapshot))
    (call $record_set (local.get $frame) (i32.const 1) (local.get $deltas))
    (local.set $new_len (i32.add (global.get $infer_branches_len_g) (i32.const 1)))
    (global.set $infer_branches_ptr
      (call $list_extend_to (global.get $infer_branches_ptr) (local.get $new_len)))
    ;; Shift-right insert at index 0
    (local.set $i (global.get $infer_branches_len_g))
    (block $shift_done
      (loop $shift
        (br_if $shift_done (i32.eqz (local.get $i)))
        (drop (call $list_set (global.get $infer_branches_ptr)
                              (local.get $i)
                              (call $list_index
                                (global.get $infer_branches_ptr)
                                (i32.sub (local.get $i) (i32.const 1)))))
        (local.set $i (i32.sub (local.get $i) (i32.const 1)))
        (br $shift)))
    (drop (call $list_set (global.get $infer_branches_ptr)
                          (i32.const 0)
                          (local.get $frame)))
    (global.set $infer_branches_len_g (local.get $new_len)))

  ;; $infer_branch_divider — capture current branch's delta into the
  ;; head frame's deltas list; reset used to base. Per src/own.mn:128-137.
  ;; No-op on empty stack (defensive per src/own.mn:129).
  (func $infer_branch_divider
    (local $frame i32) (local $base i32) (local $deltas i32)
    (local $delta i32) (local $new_deltas i32)
    (call $own_init)
    (if (i32.eqz (global.get $infer_branches_len_g)) (then (return)))
    (local.set $frame (call $list_index (global.get $infer_branches_ptr)
                                        (i32.const 0)))
    (local.set $base (call $record_get (local.get $frame) (i32.const 0)))
    (local.set $deltas (call $record_get (local.get $frame) (i32.const 1)))
    (local.set $delta (call $own_set_diff (global.get $infer_used_ptr)
                                           (local.get $base)))
    (local.set $new_deltas (call $own_list_cons (local.get $delta)
                                                (local.get $deltas)))
    (call $record_set (local.get $frame) (i32.const 1) (local.get $new_deltas))
    (call $own_used_replace (local.get $base)))

  ;; $infer_branch_exit(span, reason) — capture last branch's delta;
  ;; pairwise-check collisions; merge all deltas into used as
  ;; base ∪ union(deltas); pop frame. Per src/own.mn:143-154.
  (func $infer_branch_exit (param $span i32) (param $reason i32)
    (local $frame i32) (local $base i32) (local $prior_deltas i32)
    (local $last_delta i32) (local $all_deltas i32) (local $merged i32)
    (call $own_init)
    (if (i32.eqz (global.get $infer_branches_len_g)) (then (return)))
    (local.set $frame (call $list_index (global.get $infer_branches_ptr)
                                        (i32.const 0)))
    (local.set $base (call $record_get (local.get $frame) (i32.const 0)))
    (local.set $prior_deltas (call $record_get (local.get $frame) (i32.const 1)))
    (local.set $last_delta (call $own_set_diff (global.get $infer_used_ptr)
                                                (local.get $base)))
    (local.set $all_deltas (call $own_list_cons (local.get $last_delta)
                                                (local.get $prior_deltas)))
    (call $own_check_branch_collisions (local.get $all_deltas)
                                        (local.get $span)
                                        (local.get $reason))
    (local.set $merged (call $own_set_union
                          (local.get $base)
                          (call $own_set_union_all
                            (call $make_list (i32.const 0))
                            (local.get $all_deltas))))
    (call $own_used_replace (local.get $merged))
    (call $own_branches_pop_head))

  ;; $infer_ref_escape_check_at_return(body_handle, return_leaves, reason)
  ;; — walk state.wat's $infer_ref_escape_ptr by index; for each entry
  ;; whose name appears in the caller-built return_leaves list, emit
  ;; ref-escape diagnostic on body_handle. Per src/own.mn:371-376
  ;; check_ref_escape + walk_return_positions. The caller (walk_stmt.wat
  ;; FnStmt arm — pending) builds return_leaves via the structural
  ;; walker per §10.2 AST tag conventions.
  (func $infer_ref_escape_check_at_return (param $body_handle i32)
                                            (param $return_leaves i32)
                                            (param $reason i32)
    (local $n i32) (local $i i32) (local $entry i32)
    (local $name i32) (local $span i32)
    (call $infer_init)
    (call $own_init)
    (local.set $n (call $infer_ref_escape_len))
    (local.set $i (i32.const 0))
    (block $done
      (loop $iter
        (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
        (local.set $entry (call $list_index (global.get $infer_ref_escape_ptr)
                                            (local.get $i)))
        (local.set $name (call $record_get (local.get $entry) (i32.const 0)))
        (local.set $span (call $record_get (local.get $entry) (i32.const 1)))
        (if (call $own_list_contains_str (local.get $return_leaves)
                                          (local.get $name))
          (then
            (call $infer_emit_ref_escape
              (local.get $body_handle) (local.get $name)
              (local.get $span) (local.get $reason))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $iter))))

  ;; $infer_ref_escape_clear — defensive clear of ref-escape tracker at
  ;; FnStmt exit; delegates to state.wat's $infer_ref_escape_clear_state
  ;; (added per E2 of own.wat plan).
  (func $infer_ref_escape_clear
    (call $infer_ref_escape_clear_state))

  ;; $infer_used_clear — clear ledger at FnStmt exit. Length-only reset
  ;; per state.wat's $infer_reset_walk discipline (bump allocator never
  ;; frees; next push reuses storage).
  (func $infer_used_clear
    (call $own_init)
    (global.set $infer_used_len_g       (i32.const 0))
    (global.set $infer_used_sites_len_g (i32.const 0))
    (global.set $infer_branches_len_g   (i32.const 0)))

  ;; ═══ DIAGNOSTIC EMIT HELPERS ═══════════════════════════════════════
  ;;
  ;; Per emit_diag.wat:189-195 stated delegation: OwnershipViolation
  ;; diagnostic helpers live in own.wat, NOT emit_diag.wat. Discipline
  ;; mirrors emit_diag's $eprint_string + $graph_bind_kind +
  ;; $node_kind_make_nerrorhole pattern for productive-under-error.

  ;; $infer_emit_ownership_violation(handle, name, span, first_span, reason)
  ;; — double-consume diagnostic. Message:
  ;;   "E_OwnershipViolation: '<name>' consumed twice (first at
  ;;    <int_to_str(first_span)>')\n"
  ;; Binds handle to NErrorHole(Inferred("ownership double-consume")).
  ;; span dropped (already encoded in first_span concat); auth_hint
  ;; from src/own.mn:91-95 deferred to walk-arm composition (the seed's
  ;; helper carries the bare violation; gradient hint composition is
  ;; named follow-up Hβ.infer.gradient-hint).
  (func $infer_emit_ownership_violation (param $handle i32) (param $name i32)
                                          (param $span i32)
                                          (param $first_span i32)
                                          (param $reason i32)
    (local $msg i32)
    (local.set $msg (i32.const 3136))                                  ;; "E_OwnershipViolation: "
    (local.set $msg (call $str_concat (local.get $msg) (i32.const 3208)))   ;; "'"
    (local.set $msg (call $str_concat (local.get $msg) (local.get $name)))
    (local.set $msg (call $str_concat (local.get $msg) (i32.const 3168)))   ;; " consumed twice (first at "
    (local.set $msg (call $str_concat (local.get $msg)
                       (call $int_to_str (local.get $first_span))))
    (local.set $msg (call $str_concat (local.get $msg) (i32.const 3200)))   ;; "')"
    (local.set $msg (call $str_concat (local.get $msg) (i32.const 1912)))   ;; "\n" (emit_diag.wat data segment)
    (call $eprint_string (local.get $msg))
    (drop (local.get $span))
    (call $graph_bind_kind
      (local.get $handle)
      (call $node_kind_make_nerrorhole
        (call $reason_make_inferred (i32.const 3296)))                 ;; "ownership double-consume"
      (local.get $reason)))

  ;; $infer_emit_ref_escape(handle, name, span, reason) — ref-escape
  ;; diagnostic. Message:
  ;;   "E_OwnershipViolation: '<name>' escapes its scope (returned)\n"
  ;; Binds handle to NErrorHole(Inferred("ownership ref escape")).
  (func $infer_emit_ref_escape (param $handle i32) (param $name i32)
                                 (param $span i32) (param $reason i32)
    (local $msg i32)
    (local.set $msg (i32.const 3136))                                  ;; "E_OwnershipViolation: "
    (local.set $msg (call $str_concat (local.get $msg) (i32.const 3208)))   ;; "'"
    (local.set $msg (call $str_concat (local.get $msg) (local.get $name)))
    (local.set $msg (call $str_concat (local.get $msg) (i32.const 3208)))   ;; "'"
    (local.set $msg (call $str_concat (local.get $msg) (i32.const 3216)))   ;; " escapes its scope (returned)"
    (local.set $msg (call $str_concat (local.get $msg) (i32.const 1912)))   ;; "\n"
    (call $eprint_string (local.get $msg))
    (drop (local.get $span))
    (call $graph_bind_kind
      (local.get $handle)
      (call $node_kind_make_nerrorhole
        (call $reason_make_inferred (i32.const 3328)))                 ;; "ownership ref escape"
      (local.get $reason)))

  ;; $infer_emit_branch_collision(name, span, reason) — branch-collision
  ;; diagnostic per src/own.mn:343 (per-name violation, NOT per-handle).
  ;; Message:
  ;;   "E_OwnershipViolation: '<name>' consumed in two parallel branches\n"
  ;; Drops span AND reason (no $graph_bind_kind — the violation is
  ;; cross-branch, not bound to a single handle's gradient state).
  (func $infer_emit_branch_collision (param $name i32) (param $span i32)
                                       (param $reason i32)
    (local $msg i32)
    (local.set $msg (i32.const 3136))                                  ;; "E_OwnershipViolation: "
    (local.set $msg (call $str_concat (local.get $msg) (i32.const 3208)))   ;; "'"
    (local.set $msg (call $str_concat (local.get $msg) (local.get $name)))
    (local.set $msg (call $str_concat (local.get $msg) (i32.const 3256)))   ;; " consumed in two parallel branches"
    (local.set $msg (call $str_concat (local.get $msg) (i32.const 1912)))   ;; "\n"
    (call $eprint_string (local.get $msg))
    (drop (local.get $span))
    (drop (local.get $reason)))
